<a href="https://colab.research.google.com/github/Candida18/ADS_SMA/blob/main/ADS/8960_Candida_Noronha_ADS_Practical_2_(Inferential_Statistics).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### <b>Name: Candida Noronha<br/>
### <b>Class: BE COMPS B<br/>
### <b>Roll No.: 8960
### <b>Practical 2 - Inferential Statistics

**Z-Score**

Computing z-score using defualt values

In [ ]:
import numpy as np
import scipy.stats as stats

a = np.array([0.8976,0.9989,0.5678,0.1234,0.7765,1,1.675,1.456])
stats.zscore(a)

array([-0.08660476,  0.13662837, -0.81337952, -1.79269639, -0.35347081,
        0.13905242,  1.62653867,  1.14393202])

Computing z-score along specified axis using degrees of freedom

In [ ]:
a = np.array([[0.1234,0.4567,0.7890,0.9876],
             [0.6789,0.7890,0.9987,0.6657],
             [0.2234,0.9987,0.3345,0.5567]])

stats.zscore(a,axis=1,ddof=1)

array([[-1.22576827, -0.3486311 ,  0.52587439,  1.04852498],
       [-0.67641081,  0.03847117,  1.40005837, -0.76211873],
       [-0.88942498,  1.37202025, -0.56536131,  0.08276604]])

Computing z-score using nan_policy

In [ ]:
a = np.array([[0.1234,np.nan,0.7890,0.9876],
             [0.6789,0.7890,0.9987,0.6657],
             [np.nan,0.9987,0.3345,np.nan]])

stats.zscore(a,axis=1) # default value of nan_policy is propagate, which returns nan 


array([[        nan,         nan,         nan,         nan],
       [-0.78105192,  0.04442268,  1.61664815, -0.88001891],
       [        nan,         nan,         nan,         nan]])

**Z-Test**

In [ ]:
import numpy as np
import pandas as pd
from numpy.random import randn
from statsmodels.stats.weightstats import ztest

In [ ]:
x1 = [20, 30, 40, 50, 10, 20]
z = ztest(x1,value= 25) # where value is a mean value
z
# The first value from the above result is statistic value and the other value is pvalue. From the above output, we can understand that the pvalue of the taken data is 0.9 which is greater than the value of alpha which is 0.05. Hence we come to the output that Null Hypothesis is correct and it is accepted, which means that the given data and the assumed mean are approximately equal.


(0.5547001962252289, 0.5790997419539189)

In [ ]:
x1 = [20, 30, 40, 50, 10, 20]
x2 = [11, 12, 13, 14, 15, 16]

z=ztest(x1, x2, value= 0, alternative = 'larger')
z

(2.448717008689441, 0.007168301924196878)

From the above output, we can understand that the Null Hypothesis is rejected and Alternate Hypothesis is accepted as the pvalue is less than the alpha value


**T-Test**

**Independent t-Test**

In [ ]:
import scipy.stats as stats

a = np.array([5,6,7,8,2,3,4,5])
b = np.array([12,13,14,15,16,2,3,4])

stats.ttest_ind(a, b, equal_var=True) # Assuming that the 2 groups have equal variance

Ttest_indResult(statistic=-2.2331335038240865, pvalue=0.042379219768910015)

In [ ]:
stats.ttest_ind(a, b, equal_var=False) # Assuming that the 2 groups doesn't have equal variance

Ttest_indResult(statistic=-2.2331335038240865, pvalue=0.05369587840008499)

Understanding the result from the above test, assuming that the alpha value is 0.05, the both results assuming that the 2 groups have same variances and different variances, returns out pvalue which is less than the value of alpha. Hence the 2 bags or the 2 groups means are not supposed to be equal

Using statsmodels
statsmodels.stats.weightstats.ttest_ind(x1, x2)

where, 
    x1 and x2 are two array groups

Returns:
    tstat : float
    test statistic

    pvalue : float
    pvalue of the t-test

    df : int or float
    degrees of freedom used in the t-test

In [ ]:
from statsmodels.stats.weightstats import ttest_ind

a = np.array([12,14,16,4,5,11,12,11])
b = np.array([12,13,14,15,16,2,3,4])

ttest_ind(a,b)

(0.2963188789948769, 0.7713367820262194, 14.0)

**Paired T-test**

In [ ]:
import scipy.stats as stats

a = np.array([12, 14, 16, 4, 5, 11, 12, 11])
b = np.array([12, 13, 14, 15, 16, 2, 3, 4])

stats.ttest_rel(a,b)

Ttest_relResult(statistic=0.2635521911161371, pvalue=0.7997147761519708)

**F-Test**

In [ ]:
import numpy as np
import pandas as pd
import scipy.stats as stats


In [ ]:
cities = ["punjab","delhi","hyderabad","bangalore","mumbai"]

In [ ]:
people_of_spec_city = np.random.choice(a= cities, p = [0.05, 0.15 ,0.25, 0.05, 0.5], size=1000)
# np.random.choice, returns some random values from the given value a, with the probabilities mentioned in p of size given

people_of_spec_city

array(['bangalore', 'hyderabad', 'hyderabad', 'delhi', 'hyderabad',
       'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'mumbai',
       'delhi', 'mumbai', 'mumbai', 'mumbai', 'hyderabad', 'delhi',
       'mumbai', 'mumbai', 'mumbai', 'mumbai', 'punjab', 'hyderabad',
       'bangalore', 'mumbai', 'delhi', 'mumbai', 'hyderabad', 'hyderabad',
       'hyderabad', 'mumbai', 'hyderabad', 'hyderabad', 'delhi', 'mumbai',
       'delhi', 'delhi', 'hyderabad', 'mumbai', 'bangalore', 'mumbai',
       'mumbai', 'hyderabad', 'mumbai', 'mumbai', 'mumbai', 'hyderabad',
       'mumbai', 'hyderabad', 'mumbai', 'bangalore', 'bangalore',
       'hyderabad', 'mumbai', 'mumbai', 'hyderabad', 'mumbai',
       'hyderabad', 'delhi', 'mumbai', 'mumbai', 'hyderabad', 'mumbai',
       'mumbai', 'delhi', 'punjab', 'mumbai', 'hyderabad', 'mumbai',
       'hyderabad', 'mumbai', 'mumbai', 'mumbai', 'mumbai', 'hyderabad',
       'hyderabad', 'bangalore', 'mumbai', 'mumbai', 'mumbai', 'mumbai',
       'hyderabad

In [ ]:
population_of_spec_city = stats.poisson.rvs(loc=18,  mu=30,  size= 1000)
# stats.poisson.rvs method is used to generate random numbers, where loc is to define mean, mu is used to specify shape 
#paramters and as for the size, it defines the number of values

population_of_spec_city


array([58, 58, 45, 47, 50, 42, 39, 48, 49, 41, 42, 47, 52, 47, 45, 48, 44,
       51, 38, 48, 50, 47, 51, 39, 45, 52, 45, 55, 49, 56, 48, 54, 44, 52,
       51, 49, 50, 36, 44, 55, 43, 49, 60, 49, 47, 48, 45, 44, 44, 35, 48,
       54, 49, 42, 50, 47, 55, 50, 48, 46, 49, 43, 44, 47, 48, 54, 46, 49,
       43, 52, 40, 49, 58, 51, 44, 42, 47, 50, 45, 59, 43, 46, 55, 52, 44,
       46, 54, 54, 52, 46, 48, 49, 39, 54, 51, 42, 48, 57, 52, 49, 47, 55,
       59, 36, 45, 50, 48, 51, 44, 42, 46, 47, 56, 47, 47, 53, 38, 40, 47,
       47, 49, 41, 52, 50, 39, 55, 36, 45, 55, 43, 40, 52, 46, 53, 52, 44,
       55, 52, 54, 46, 42, 50, 42, 52, 44, 37, 44, 45, 43, 48, 50, 57, 47,
       47, 38, 50, 50, 52, 53, 57, 48, 39, 46, 57, 45, 43, 42, 58, 38, 54,
       48, 52, 44, 52, 59, 40, 63, 37, 40, 48, 50, 64, 43, 52, 44, 40, 42,
       52, 49, 57, 53, 52, 54, 51, 53, 48, 46, 49, 43, 50, 43, 66, 57, 53,
       50, 51, 49, 46, 48, 54, 55, 49, 49, 52, 40, 41, 50, 46, 40, 47, 52,
       46, 53, 51, 60, 38

In [ ]:
# Forming the Dataframe from the obatined values
population_frame = pd.DataFrame({"city":people_of_spec_city,"population":population_of_spec_city})

# Dividing these values by the categorical variables into groups
groups = population_frame.groupby("city").groups

groups

{'bangalore': [0, 23, 39, 50, 51, 76, 88, 90, 118, 124, 171, 178, 189, 211, 222, 224, 264, 302, 307, 319, 366, 378, 434, 449, 494, 497, 507, 510, 566, 568, 609, 611, 621, 628, 645, 681, 747, 770, 784, 796, 808, 809, 853, 858, 862, 899, 923, 940, 944, 955, 960, 968, 985, 998], 'delhi': [3, 11, 16, 25, 33, 35, 36, 58, 64, 87, 97, 108, 110, 111, 115, 119, 133, 136, 137, 141, 151, 153, 162, 167, 174, 181, 183, 186, 200, 220, 238, 253, 256, 269, 277, 285, 292, 306, 308, 311, 313, 314, 318, 340, 350, 356, 372, 374, 398, 401, 409, 412, 413, 420, 432, 436, 437, 441, 445, 451, 453, 460, 471, 477, 489, 498, 500, 503, 522, 524, 527, 531, 536, 540, 558, 573, 589, 591, 597, 598, 601, 607, 612, 616, 626, 632, 642, 646, 654, 668, 677, 684, 685, 687, 688, 694, 697, 708, 718, 723, ...], 'hyderabad': [1, 2, 4, 15, 22, 27, 28, 29, 31, 32, 37, 42, 46, 48, 52, 55, 57, 61, 67, 69, 74, 75, 81, 85, 94, 101, 102, 109, 112, 121, 126, 128, 130, 132, 140, 144, 149, 150, 152, 154, 156, 160, 161, 163, 164, 166, 170

In [ ]:
asian = population_of_spec_city [groups["punjab"]]
black = population_of_spec_city[groups["bangalore"]]
hispanic = population_of_spec_city[groups["delhi"]]
other = population_of_spec_city[groups["hyderabad"]]
white = population_of_spec_city[groups["mumbai"]]

In [ ]:
stats.f_oneway(asian, black, hispanic, other, white)

F_onewayResult(statistic=1.1702346131741366, pvalue=0.3223375721204956)

**Correlation coefficients**

In [ ]:
from google.colab import drive
drive.mount('/content/drive/MyDrive/Applied Data Science/Experiment2/happyscore_income.csv')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('/content/drive/MyDrive/Applied Data Science/Experiment2/happyscore_income.csv',index_col=0)
df.head()


adjusted_satisfaction  avg_satisfaction  std_satisfaction  \
country                                                                
Armenia                     37.0               4.9              2.42   
Angola                      26.0               4.3              3.19   
Argentina                   60.0               7.1              1.91   
Austria                     59.0               7.2              2.11   
Australia                   65.0               7.6              1.80   

           avg_income  median_income  income_inequality  \
country                                                   
Armenia       2096.76    1731.506667          31.445556   
Angola        1448.88    1044.240000          42.720000   
Argentina     7101.12    5109.400000          45.475556   
Austria      19457.04   16879.620000          30.296250   
Australia    19917.00   15846.060000          35.285000   

                                  region  happyScore      GDP  country.1  
country                                                                   
Armenia     'Central and Eastern Europe'       4.350  0.76821    Armenia  
Angola              'Sub-Saharan Africa'       4.033  0.75778     Angola  
Argentina  'Latin America and Caribbean'       6.574  1.05351  Argentina  
Austria                 'Western Europe'       7.200  1.33723    Austria  
Australia    'Australia and New Zealand'       7.284  1.33358  Australia

In [ ]:
df.corr(method='pearson')

adjusted_satisfaction  avg_satisfaction  \
adjusted_satisfaction               1.000000          0.978067   
avg_satisfaction                    0.978067          1.000000   
std_satisfaction                   -0.527553         -0.341201   
avg_income                          0.728006          0.689043   
median_income                       0.704383          0.661883   
income_inequality                  -0.123835         -0.082471   
happyScore                          0.901213          0.885988   
GDP                                 0.755578          0.776679   

                       std_satisfaction  avg_income  median_income  \
adjusted_satisfaction         -0.527553    0.728006       0.704383   
avg_satisfaction              -0.341201    0.689043       0.661883   
std_satisfaction               1.000000   -0.478206      -0.481429   
avg_income                    -0.478206    1.000000       0.995605   
median_income                 -0.481429    0.995605       1.000000   
income_inequality              0.221831   -0.382587      -0.449053   
happyScore                    -0.457896    0.782122       0.760328   
GDP                           -0.242038    0.814024       0.797905   

                       income_inequality  happyScore       GDP  
adjusted_satisfaction          -0.123835    0.901213  0.755578  
avg_satisfaction               -0.082471    0.885988  0.776679  
std_satisfaction                0.221831   -0.457896 -0.242038  
avg_income                     -0.382587    0.782122  0.814024  
median_income                  -0.449053    0.760328  0.797905  
income_inequality               1.000000   -0.187222 -0.303204  
happyScore                     -0.187222    1.000000  0.790061  
GDP                            -0.303204    0.790061  1.000000

In [ ]:
df.corr(method='spearman')

adjusted_satisfaction  avg_satisfaction  \
adjusted_satisfaction               1.000000          0.981629   
avg_satisfaction                    0.981629          1.000000   
std_satisfaction                   -0.497192         -0.354810   
avg_income                          0.803010          0.808310   
median_income                       0.779671          0.782479   
income_inequality                  -0.168049         -0.137139   
happyScore                          0.900697          0.893395   
GDP                                 0.766098          0.773521   

                       std_satisfaction  avg_income  median_income  \
adjusted_satisfaction         -0.497192    0.803010       0.779671   
avg_satisfaction              -0.354810    0.808310       0.782479   
std_satisfaction               1.000000   -0.317653      -0.309697   
avg_income                    -0.317653    1.000000       0.990839   
median_income                 -0.309697    0.990839       1.000000   
income_inequality              0.182610   -0.356069      -0.448926   
happyScore                    -0.421175    0.819542       0.806704   
GDP                           -0.275832    0.960969       0.961583   

                       income_inequality  happyScore       GDP  
adjusted_satisfaction          -0.168049    0.900697  0.766098  
avg_satisfaction               -0.137139    0.893395  0.773521  
std_satisfaction                0.182610   -0.421175 -0.275832  
avg_income                     -0.356069    0.819542  0.960969  
median_income                  -0.448926    0.806704  0.961583  
income_inequality               1.000000   -0.242107 -0.409767  
happyScore                     -0.242107    1.000000  0.793673  
GDP                            -0.409767    0.793673  1.000000

In [ ]:
df.corr(method='kendall')

adjusted_satisfaction  avg_satisfaction  \
adjusted_satisfaction               1.000000          0.905145   
avg_satisfaction                    0.905145          1.000000   
std_satisfaction                   -0.378239         -0.266347   
avg_income                          0.614896          0.618270   
median_income                       0.593379          0.593810   
income_inequality                  -0.124810         -0.104128   
happyScore                          0.741682          0.732966   
GDP                                 0.581131          0.591166   

                       std_satisfaction  avg_income  median_income  \
adjusted_satisfaction         -0.378239    0.614896       0.593379   
avg_satisfaction              -0.266347    0.618270       0.593810   
std_satisfaction               1.000000   -0.237797      -0.233515   
avg_income                    -0.237797    1.000000       0.929566   
median_income                 -0.233515    0.929566       1.000000   
income_inequality              0.124672   -0.229994      -0.299779   
happyScore                    -0.320795    0.622277       0.614087   
GDP                           -0.205190    0.841441       0.847011   

                       income_inequality  happyScore       GDP  
adjusted_satisfaction          -0.124810    0.741682  0.581131  
avg_satisfaction               -0.104128    0.732966  0.591166  
std_satisfaction                0.124672   -0.320795 -0.205190  
avg_income                     -0.229994    0.622277  0.841441  
median_income                  -0.299779    0.614087  0.847011  
income_inequality               1.000000   -0.166762 -0.264067  
happyScore                     -0.166762    1.000000  0.601310  
GDP                            -0.264067    0.601310  1.000000

In [ ]:
from scipy.stats import chisquare

**With f_obs values**

In [ ]:
f_obs=[16, 12, 16, 18, 14, 12]
chisq=chisquare(f_obs).statistic
pvalue=chisquare(f_obs).pvalue
print("chisquare statistic :",chisq)
print("p_value :",pvalue)

chisquare statistic : 2.0
p_value : 0.8491450360846096


**With f_exp and f_obs values**

In [ ]:
f_obs=[16, 12, 16, 18, 14, 12]
f_exp=[16, 8, 16, 16, 16, 16]
chisquare(f_obs,f_exp)

Power_divergenceResult(statistic=3.5, pvalue=0.6233876277495822)

**With f_obs as 2d**

In [ ]:
f_obs=[[16, 12, 16, 18, 14, 12],[24, 12, 32, 16, 32, 12]] # The test is automatically applied to each column
chisquare(f_obs)

Power_divergenceResult(statistic=array([1.6       , 0.        , 5.33333333, 0.11764706, 7.04347826,
       0.        ]), pvalue=array([0.20590321, 1.        , 0.02092134, 0.73160059, 0.00795544,
       1.        ]))

**With axis as None**

In [ ]:
f_obs=[[16, 12, 16, 18, 14, 12],[24, 12, 32, 16, 32, 12]] # The test is applied to the whole data
chisquare(f_obs, axis=None)

Power_divergenceResult(statistic=33.33333333333333, pvalue=0.0004645423926184954)

***With axis as 1***

In [ ]:
f_obs=[16, 12, 16, 18, 14, 12]
f_exp=[[16, 12, 16, 18, 14, 12],[16, 8, 16, 16, 16, 16]]
chisquare(f_obs,f_exp,axis=1)

Power_divergenceResult(statistic=array([0. , 3.5]), pvalue=array([1.        , 0.62338763]))

**With ddof specified**

In [ ]:
f_obs=[16, 12, 16, 18, 14, 12]
chisquare(f_obs, ddof=1)

Power_divergenceResult(statistic=2.0, pvalue=0.7357588823428847)

In [ ]:
chisquare(f_obs,ddof=[0,1])

Power_divergenceResult(statistic=2.0, pvalue=array([0.84914504, 0.73575888]))

In [ ]:
chisquare(f_obs,ddof=[0,1,2])

Power_divergenceResult(statistic=2.0, pvalue=array([0.84914504, 0.73575888, 0.5724067 ]))